# Generated by Django 4.0.6 on 2022-07-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoreis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(max_length=100)),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.TextField()),
                ('auth_user_id', models.TextField()),
                ('metatitle', models.TextField()),
                ('metakeyword', models.TextField()),
                ('description', models.TextField(max_length=100)),
                ('heading', models.TextField()),
                ('shortstory', models.TextField(max_length=500)),
                ('fullstory', models.TextField(max_length=5000)),
                ('featureimg', models.TextField()),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
            ],
        ),
    ]
